headers_apple = {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0',
    'Accept': '*/*',
    'Accept-Language': 'en-GB,en;q=0.5',
    'Accept-Encoding': 'gzip, deflate, br',
    'Referer': 'https://music.apple.com/',
    'authorization': 'Bearer XXXXXXXXXXXXXXXXXXXXX',
    'Origin': 'https://music.apple.com',
    'DNT': '1',
    'Connection': 'keep-alive',
    'Cookie': 'XXXXXXXXXXXXXXXXXXXXX',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-site',
}